# Netlify configuration file

# Global headers to control security policies
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "frame-ancestors 'self'"
    Permissions-Policy = "interest-cohort=(), storage-access=(self)"

# Proxy configuration to forward API requests to Railway backend
[[redirects]]
  from = "/api/*"
  to = "https://qrattendance-backend-production.up.railway.app/:splat"
  status = 200
  force = true
  
  # Headers to enable CORS
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept, X-User-ID, X-User-Role"
    Access-Control-Allow-Credentials = "true"

# Handle routing for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 